### ISSUE TITLE
apkid crash

### ISSUE THREAD

**Issue by idanr1986** [rednaga/APKiD#15]
this sample crashes apkid:
900b5a460be3e150420598beb41ea0a15d23a05e57f0f9383600844fac49cd85

[!] APKiD 0.9.4 :: from RedNaga :: rednaga.io
fish: 'apkid <path>…' terminated by signal SIGSEGV (Address boundary error)

**Comment by strazzere** [comment]
Interesting - this file is a bit weird. It did not SIGSEGV for me, however I believe some of the code has been refactored since you posted this.

```
diff@rigby:[crashes-apkid]$ apkid 
[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io
diff@rigby:[crashes-apkid]$ apkid 900b5a460be3e150420598beb41ea0a15d23a05e57f0f9383600844fac49cd85 
[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io
2017-05-04 16:50:03 ERROR    error scanning: could not map file "900b5a460be3e150420598beb41ea0a15d23a05e57f0f9383600844fac49cd85" into memory
diff@rigby:[crashes-apkid]$ file 900b5a460be3e150420598beb41ea0a15d23a05e57f0f9383600844fac49cd85 
900b5a460be3e150420598beb41ea0a15d23a05e57f0f9383600844fac49cd85: Dalvik dex file version 035
```

The file seems be truncated -- as the size of the file, indicated by the head is `345296` -- however it actually is `341913`. This means that the map section that has an offset of `345148` has been cut off. Essentially, this is an invalid file that shouldn't work.

I'll dig into this deeper later to potentially produce a better error than "unable to map", though as I said, it seems the SIGSEGV is taken care of already.

**Comment by strazzere** [comment]
Closing this issue as it is rather dated and already fixed.
