### ISSUE TITLE
yara.SyntaxError: apkid/rules/dex/abnormal.yara(107): invalid field name "invalid_dex"

### ISSUE THREAD

**Issue by jbdsfks** [rednaga/APKiD#18]
Dear author.When I run ./prep-release.py, I got a problem like this in the [picture](http://i1.piimg.com/4851/174d74ebfe83bb39.png) behind.I would appreciate it if you help me to solve this issue.

**Comment by CalebFenton** [comment]
I believe this is caused because some changes were made to the DEX module in our fork of yara-python. Try uninstalling yara-python and updating yara-python. The pip build thing is a little weird, and it's probably easier to just clone yara-python fresh and install it from there.

Try that and let me know how it works.

**Comment by jbdsfks** [comment]
I have removed it and it can be work now! Thank you.

**Comment by CalebFenton** [comment]
Need to install latest version of our yara-python fork. Dex module was
improved
