### ISSUE TITLE
Add tags to tool description

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#205]
These are the tags in the description:

- android
- antivirus
- machine-learning
- malware-detection
- malware-analysis
- malware-research
- yara
- yara-forensics

What about to add `RASP` and `appshielding`?

**Comment by CalebFenton** [comment]
Thanks for the suggestion.

I didn't add these originally because we don't actually do any of those things. If you're searching for android packers, you probably don't want to find apkid. But it's kinda related, and it's costless to add, and might be useful if there are any sort of magical correlated / intelligent search algorithms digging up project pages.

Neither `RASP` nor `appshielding` show up in the auto-complete list, but I added them. I've never seen either, and I had to look up RASP. I also added some options that do appear in the auto-complete list that are related to packers.
