### ISSUE TITLE
APKiD was integrated in Intel Owl - easy to use GUI

### ISSUE THREAD

**Issue by Eshaan7** [rednaga/APKiD#232]
Hi. We at [Intel Owl](https://github.com/intelowlproject/IntelOwl) recently added support for APKiD.

Intel Owl is a completely free and open source threat intelligence gathering tool that integrates a lot of external services and analyzers. If someone wants to request a APKiD scan they can do so easily with Intel Owl's web GUI - get the JSON result in a prettified format which can be filtered/sorted/search through and is saved into the DB.

> This is NOT meant to be an "advertisement" for Intel Owl nor a replacement to APKiD - We simply support APKiD and these are some nice features for APKiD users to speed up their threat intelligence operations.

I hope you don't mind and thank you for creating this amazing tool!

**Comment by strazzere** [comment]
Hi there! Thanks for the heads up - this is fine assuming all licensing requirements are met. Skimming the Intel Owl repo, as it is a FOSS tool this is fine. Though it might be worth noting somewhere in your repo that the tool is /not/ free for commercial usage. Nice looking project!

As long as it is not included into a "pay" version of this tool, or used as a commercial/corporate workflow, this is fine.

If someone using Intel Owl for the above purposes comes across this, please reach out to us. We are not asking for much - just a minimal licensing fee to assisting in maintenance of the project, often these are just donated when they come in. Though it is important to abide by this as we want to prevent people reselling this code, which results in us getting nasty emails and support requests... (Since people "paid for this... but didn't "pay" us anything)

**Comment by Eshaan7** [comment]
Thankyou for your prompt response, @strazzere. 

> Though it might be worth noting somewhere in your repo that the tool is /not/ free for commercial usage

We have a [Legal Disclaimer](https://github.com/intelowlproject/IntelOwl#legal-notice) in our project's README for this purpose only. I will make sure to add a link to APKiD's `LICENSE.commercial` there. Does this sound okay to you ?

**Comment by CalebFenton** [comment]
@Eshaan7 that would be great, thanks.
