### ISSUE TITLE
APKiD yara rules are not compatible in BlackArch repositories

### ISSUE THREAD

**Issue by AkechiShiro** [rednaga/APKiD#318]
Hi, we've been getting an issue recently on the APKiD package, but we haven't been able to find a solution, I'm not sure if something changed upstream that could explain this bug : https://github.com/BlackArch/blackarch/issues/3296

**Comment by CalebFenton** [comment]
This can happen if the compiled Yara rules file was compiled with a different version of Yara that's being used to run it. We use a fork of Yara that only has a change that enables dex file support, so it's easy to update if that's the problem. I should be able to look at this tomorrow but it should be an easy fix.

May need to update Yara for apkid or for blackarch. Maybe Apkid can just recompile rules on first run, but this will only work for Yara compiled with dex support.

**Comment by AkechiShiro** [comment]
Any news on this issue so far ? Or any workaround you could recommend ? We could do an update for the yara package in BlackArch, we're currently using this fork from `rednaga` with I believe dex enabled as well : https://github.com/rednaga/yara-python-1

**Comment by CalebFenton** [comment]
The root cause is you have different version of yara than the one that was used to compile the rules. I believe yara-python-dex is providing the yara library, so the problem is probably BlackArch has a conflicting version of yara binary on the load path. This could be from a python or system package. Any fix will need to address this, either by removing the conflicting packages or changing how apkid looks for libraries.

You can stop using the deprecated fork of yara-python. We switched to the yara-python-dex repo because it simplified installing -- you should just be able to `pip install apkid` and get the current version (2.1.4). That may fix your problem.

apkid requires 1.0.1 of yara-python-dex, but the latest version is 1.0.3. I tested if this matters and it doesn't. The compiled rules are compatible with both versions, but it wouldn't hurt for us to update the pinned version.

If you can give me the output of `pip freeze` from BlackArch, that may save me the time of spinning up a VM :)

The root cause is you have different version of yara than the one that was used to compile the rules. The yara binary IIRC is provided by yara-python

**Comment by AkechiShiro** [comment]
Sorry for the delay of my response.

A current `pip freeze` on my current setup shows this for `yara` and `apkid`:
```
apkid==2.1.1
yara-python==4.1.0
```
The `yara-python` comes from this package, I believe : https://github.com/rednaga/yara-python-1

Using a virtual env and doing `pip install apkid` fixes the issue indeed, it installs the latest apkid and yara-python-dex : `Successfully installed apkid-2.1.4 yara-python-dex-1.0.3`

I've package `python-yara-dex` for BlackArch and installing its latest version with `apkid` from BlackArch's repo solves the issue, thanks a lot for your help ! I'll try to move things upstream so that it fixes the original issue.

**Comment by CalebFenton** [comment]
Glad you got it sorted. Very cool to see apkid included in pentesting distros :)
