### ISSUE TITLE
anti_vm recommendation

### ISSUE THREAD

**Issue by 89z** [rednaga/APKiD#323]
For people getting the `anti_vm` result, such as:

~~~
anti_vm : Build.FINGERPRINT check, Build.MANUFACTURER check, Build.TAGS check,
network operator name check
~~~

do you have some recommendation for a Frida script? This repo is useful for determining the problem, but then users currently seem to be on their own to find solutions

**Comment by strazzere** [comment]
It's up to the user to figure out what are the correct steps for this. Just because this is used, does not tell you how or what choices are made by the applicaiton.

E.g. --- if the manufacturer needs to be `Samsung`, you need to return that. If it needs to _not_ be Samsung, you need to not return that. Reversing the application is correct path.

These rules are in place to identify "indicators" or things to potentially look for that could be of interest to a reverser.

**Comment by 89z** [comment]
Thanks for the info. In my case, the `anti_vm` was actually a red herring, and the actual problem was a request header needed to be removed
